language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer install --prefer-source

before_script:
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; fi

script:
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - if [ $TRAVIS_PHP_VERSION = '7.3' ]; then php vendor/bin/test-reporter; fi